#!/bin/bash

# Sink names identified with `pactl list short sinks`.

set -eux
set -o pipefail

pactl unload-module module-combine-sink || exit 1
pactl unload-module module-loopback || exit 1
pactl unload-module module-null-sink || exit 1
pactl unload-module module-remap-sink || exit
pactl unload-module module-stream-restore || exit 1

pactl load-module module-stream-restore restore_device=false || exit 1
pactl set-default-sink alsa_output.platform-fef05700.hdmi.hdmi-stereo || exit 1

echo "Sinks:"
pactl list short sinks || exit 1

echo "Sink inputs:"
pactl list short sink-inputs || exit 1

echo "Test with \`play-left-right-test\` or \"https://www.youtube.com/watch?v=6TWJaFD6R2s\"" || exit 1
